### PR TITLE
Add debouncing when writing output prop

### PR DESCRIPTION
**Pull request by sethyuan**
I find that if `upsertBlockProperty` is called too rapidly in succession, it won't write correctly, so I added a debouncing behavior.

### CODE REVIEW

**Comment by sethyuan** [comment]
> Thanks! Any reason why you like this particular library for debouncing?

No particular reason, it's a library I often use.

BTW, there is still issues with output writing, I think it's related to the event listeners. I'll investigate further.

**Comment by sethyuan** [comment]
It's ready now.

**Comment by benjypng** [comment]
I prefer rxjs, but as long as it works! Thanks!

**Comment by sethyuan** [comment]
@hkgnp You may want to release a version since this PR contains a bug fix for assets bundling that was introduced by the last release. 😅

**Pull request merged**
